# Generated by Django 3.1.5 on 2021-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210111_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_address',
            field=models.CharField(max_length=255, verbose_name='Адрес организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
