# Generated by Django 3.1.5 on 2021-01-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210111_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'План-схема', 'verbose_name_plural': 'План-схемы'},
        ),
    ]
