# Generated by Django 3.1.5 on 2021-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_scheme',
            field=models.ImageField(upload_to='orders/service', verbose_name='Изображение план-схемы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count_images',
            field=models.IntegerField(verbose_name='Количество план-схем'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.TimeField(auto_now_add=True, verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название услуги'),
        ),
    ]
